name: Automated Documentation
run-name: updating documentation after changes by ${{ github.actor }}
on: [push]
jobs:
  document-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install and Run Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          doxygen
